### PR TITLE
Consume Snippets API

### PR DESCRIPTION
**Pull request by joefitzgerald**
Merge when atom 0.183.0 is out

This PR seeks to integrate autocomplete-plus with [snippets](https://github.com/atom/snippets) such that snippets.insert can be used to dynamically insert anonymous snippets into the current editor. This will allow autocomplete-plus providers to include anonymous snippets as part of their suggestions, giving a richer experience (particularly when confirming a suggestion which is a function, allowing us to expand the arguments automatically and allow the user to tab through them).

See https://github.com/atom/snippets/pull/106 / https://github.com/atom/snippets/pull/110

- [x] Consume Snippets API
- [x] Allow insertion of anonymous snippets from suggestions
- [x] Specs

### CODE REVIEW

**Comment by benogle** [comment]
screen shot 2015-02-19 at 5 27 10 pm

I'm using the same `word` attribute of the match to insert the snippet, and detecting the the snippet replacements in the view. 

I am not super fond of the implicit usage of snippets, but I would rather it than introduce a new attribute to the API at this point. I am really not a fan of the current attribute name `word`, which I would like to change along with this explicit snippet attribute. I was thinking something like `replacementText` and `replacementSnippet`. At this point, I would like to be minimally disruptive to the API, then do a pass renaming and cleaning up the API. 

I am not a fan of the `isSnippet` bool as it is just something extra for the user to set. We can favor the `replacementSnippet` over the `replacementText`

**Comment by joefitzgerald** [comment]
Yeah, I'm ok with that. Not tied to word. It seems like a vestige of FuzzyProvider.

**Comment by benogle** [comment]
I've changed my mind on the implicit word usage. After thinking about the upgrade path, I'd like to add `replacementSnippet` now. I assume that even if we dont document this and indicate that it's experimental, people will start to use it, and then we'll need to tease apart the implicitly set symbols. So now, I'd rather accept `replacementSnippet` now, and not publicize it until an API pass has been done as it may change.

**Comment by joefitzgerald** [comment]
We could just call it snippet instead of replacementSnippet. And add text as the alternative. The order of precedence would be snippet > text > word.

**Comment by benogle** [comment]
I want to be clear that it is the replacement.

**Comment by joefitzgerald** [comment]
@benogle should we close this in deference to #276?

**Comment by benogle** [comment]
No. I wanted to make a decision on naming before merging this. I think we should merge this (after some changes) with the correct property name.

**Comment by joefitzgerald** [comment]
Gotcha, makes sense.

**Comment by benogle** [comment]
This can be merged when atom 183 is out. We depend on snippets to have the service API: https://github.com/atom/atom/commit/eb868fdec62a168b52458bdc4fc51b95799a4370

**Pull request merged**
