### PR TITLE
Docstring in suggestions

### PR DESCRIPTION
**Pull request by tinloaf**
I moved this from #347 to here, since I originally forgot to open a feature branch. Sorry about that.

I have now:
* Rebased
* Used a template
* Written a Spec for the display of the docstring

Regarding the spec: I am not entirely certain if that worked. If I run my package specs, Atom tells me "6/6 successful, 120 skipped". Im am not sure if the new spec is skipped (and if so, why), or how to tell Atom not to skip any specs...

### CODE REVIEW

**Comment by tinloaf** [comment]
OK, looks like travis is actually running the Spec. Would be awesome if my Atom ran it, too. :-/

**Comment by basarat** [comment]
> OK, looks like travis is actually running the Spec. Would be awesome if my Atom ran it, too. :-/

`apm test` seems more reliable

**Comment by tinloaf** [comment]
Could it be that AppVeyor is somehow broken? The problem seems to be that the build times out...

**Comment by joefitzgerald** [comment]
Yes the Appveyor build us known to be flakey. You can ignore it for now.

**Comment by sveale** [comment]
Why hasn't this been accepted yet?

**Comment by benogle** [comment]
It has not been reviewed yet.

**Comment by tinloaf** [comment]
By the way - any ideas how to render a "safe subset" of Markdown? We basically don't want anything to introduce line breaks there... I've looked into a couple of libraries, but none seemed like what I wanted. I also thought about just filtering out unwanted HTML, but that seems hacky. So seems rendering links and whatever we want by hand...

**Pull request closed without merging**
