### PR TITLE
Add SymbolProvider

### PR DESCRIPTION
**Pull request by benogle**
This is a WIP. 

The current base provider is pretty terrible. As you know it just grabs a list of words from the buffer, anything in the comments, numbers, whatever. I spend 90% of the time using autocomplete dismissing it because the suggestions are garbage (unless I type almost the entire thing).

I wanted to make the defaults better. I experimented with ctags (like in symbols view), but the support for modern languages is no bueno. Turns out we already have a tokenized version of each file in the editor :tada:, so why not use that?

screen shot 2015-01-29 at 5 29 10 pm

This `SymbolProvider` selects types of tokens / symbols via scope selectors, and gives them names like `function`, `class`, etc. But these are just the default. The idea is to make this configurable from the language packages just like `editor.completions`. 

My vision for configurability is something like this:

```coffee
# For Coffee
'.source.coffee':
  'editor':
    'completionSymbols':
      class:
        selector: '.class.name'
        priority: 3
      function:
        selector: '.function'
        priority: 2
      variable:
        selector: '.variable'
        priority: 1

# For Less
'.source.css.less':
  'editor':
    'completionSymbols':
      'mixin':
        selector: '.mixin'
      'variable':
        selector: '.variable'
        wordRegex: /\b@?\w*[a-zA-Z_-]+\w*\b/g
```

Additionally, the results could be combined in a better way. Things in the buffer are likely more important than builtins. And locality would be a huge help.

Suggestions welcome.

### TODO

* [ ] Decide on what we should configure
* [x] Reconcile some symbols that are variables in one part of the file, and, say a function or class in another. 
* [x] Mess with locality scoring
* [x] Specs

cc @kevinsawicki @nathansobo

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Hurray!!!!

**Comment by park9140** [comment]
@benogle, really looking forward to this!

**Comment by benogle** [comment]
I urge you guys to try this branch out and see if the results feel better. I added the type reconciliation, and I added an experiment with locality scoring, so matches closer to where you are are scored higher. 

This really highlights how crappy the grammars are in a lot of cases. e.g. javascript doesnt even tag variables as variables (or anything, for that matter), the `less` grammar doesnt properly tag the property names or values (css does though), etc. Grammar improvements would be the biggest gain in making the results of a provider like this better.

**Comment by joefitzgerald** [comment]
We need to rebase this on master, or merge master up and resolve conflicts (mostly will be caused because we edited FuzzyProvider. Which path do you want to take?

**Comment by joefitzgerald** [comment]
> This really highlights how crappy the grammars are in a lot of cases. e.g. javascript doesnt even tag variables as variables (or anything, for that matter), the less grammar doesnt properly tag the property names or values (css does though), etc. Grammar improvements would be the biggest gain in making the results of a provider like this better.

I see that as a huge positive. If the grammars need to be improved to better reason over the source, that's exactly where the improvements should be made. It will have many follow-on benefits, including allowing grammar-specific providers to be more targeted and allowing better blacklisting of autocomplete in particular scope(s).

**Comment by benogle** [comment]
I'll rebase it. But it doesnt need to be rebased to use it. Especially if the changes were just in FuzzyProvider.

> I see that as a huge positive

Yeah I wasnt complaining. It was just surprising to me. I thought they were much better at tagging things.

**Comment by joefitzgerald** [comment]
That the JavaScript and less grammars are poor is indeed very surprising!

**Comment by park9140** [comment]
@benogle, tried this out in python, c#, c++, coffee, javascript, typescript, markdown. 

We should probably be pulling any keywords the grammar defines,  "var, function, class ....".  

In general all the languages all felt very sparse.  Perhaps it should have a priority order of things to look for to complete as pulled by the syntax. Maybe fall back through variables, functions, keywords, then 'words'.  Only go on to the next fallback if we have found less than 5 options, and only go to 'words' if it finds nothing else.

**Comment by joefitzgerald** [comment]
What additional things are required for us to retire `FuzzyProvider` in favor of this? I'm completely fine with a temporary regression in quality if it shines the spotlight on grammars, and the need to make changes there to make this work well.

What other gotchas should we be aware of? And how can @park9140 and I help?

**Comment by benogle** [comment]
> We should probably be pulling any keywords the grammar defines, "var, function, class ....".

Agreed. Though, I'd like to do that from `editor.completions` in each grammar rather than picking them out of the buffer so they are complete. 

> In general all the languages all felt very sparse. 

Yeah, I think they need to really be tailored to each language in the settings. The biggest advantage for increasing quality would be improving the grammars.

> Perhaps it should have a priority order of things to look for to complete as pulled by the syntax. Maybe fall back through variables, functions, keywords, then 'words'. Only go on to the next fallback if we have found less than 5 options, and only go to 'words' if it finds nothing else.

Yeah falling back can be experimented with. The priority could be mixed in like the locality score. The main thing that I hated about the fuzzy provider was all the false positives. So I want to be careful adding a bunch of extra things in that just add noise. 

> What additional things are required for us to retire FuzzyProvider in favor of this?

@joefitzgerald honestly, I want to sit on this for a bit. I want to use it and make sure it's doing the right thing in most cases and tinker with it while I'm using it. I am, as I'm sure you're aware, really nervous about jumping into new APIs. Once this is released, people will start updating grammars to take advantage, and I dont want to have to change it right away.

My initial motivation for doing this (and the other recent PRs) is getting autocomplete to the point where I can use it for more than a few minutes without getting frustrated and turning it off. So I want to continue down that path for a bit longer.

**Comment by joefitzgerald** [comment]
@benogle perhaps we should create a new branch with the FuzzyProvider _kept in_, and a feature to toggle the built-in provider to FuzzyProvider or SnippetsProvider, so we can ship it, and allow its active used, but keep FuzzyProvider as the default.

**Comment by benogle** [comment]
Can I just have this PR open for a few more days?

**Comment by joefitzgerald** [comment]
Of course, sorry I don't want to come across as rushing you! Just excited to make progress on an alternative to FuzzyProvider.

**Comment by lierdakil** [comment]
This looks very promising, but I like FuzzyProvider for my text documents. Thing is, I often write articles with long and very specific terminology. Being able to autocomplete those is a nice feature, actually. Saves a bit of time on typing and spellchecking.

**Comment by park9140** [comment]
@lierdakil, As a first step we should probably break fuzzy provider out into it's own package for people who like that sort of thing. 

Would it be better to have a more specific autocomplete plugin for writing?  It seems like you would want something that not only looks at terminology in your single article but also can do sentence breakdown to provide intelligent completions.   You could do weighted completions for word options from a thesaurus based on over use in your article.   If you could get access to something like the algorithms used by something like the swiftkey keyboard on android you could even guess the next logical words based on a live user profile that takes into account your personal writing habits.

**Comment by lierdakil** [comment]
@park9140, swiftkey is no magic, it most likely uses Markov chains for next-word predictions. It's not exactly rocket science, and predictions are not very accurate (to my experience anyway). Having a provider pulling words from current buffer (with a bit of fuzz) is usually more than enough for my needs. Grammar analysis is probably overkill (although implementing weighting based on Markov model could be nice -- in theory -- and relatively simple).
More to the point, moving FuzzyProvider to separate package is fine with me, and might actually be a good thing, now that I think about it.

**Comment by park9140** [comment]
@lierdakil, yeah, swiftkey just acts as a good example of implementation, even if is flawed.  I'm sure there are many great ways doing efficient natural language suggestions.  Need to find someone who understands the domain to work on a completion provider.

**Comment by nathansobo** [comment]
I need to discuss this more with @benogle, but I too am a fan of the fairly unintelligent "words from buffer" approach. I think the main difference is that I use the manually triggered autocomplete, which allows you to fuzzy find on the results. If the autocomplete is auto-triggered, fuzzy finding on the results doesn't really work because you're actually typing in the buffer at that point. Then having more completion alternatives becomes more of a liability. Not sure how to reconcile these as there's a legitimate use case for both ways of triggering.

**Comment by joefitzgerald** [comment]
It feels like extracting FuzzyProvider into an external provider would make the most sense once we have a more contextually relevant built-in provider (which this PR may represent, if @benogle wants to proceed with it).

Regarding typing to filter the fuzzy results >> how is this any different than typing in the editor? I find the context switching (into a filter in the suggestion list) jarring in that the focus changes - too often (i.e. 99% of the time) I find myself pressing escape because I want to keep typing in the editor. Because filtering continues to occur as you keep typing, the number of suggestions decreases as the word length increases, which is functionally identical to filtering the suggestion list in a suggestion list filter input - with the exception that I can continue typing in the buffer if I don't like any of the options.

**Comment by benogle** [comment]
@joefitzgerald I've totally come around to adding this as an option. I really really do not want to start adding config to the grammars to take advantage of this until it is the default though. For now, one could add to their user config to experiment with better completions with the symbol provider. 

In many cases the grammars need to be upgraded to properly tokenize, which is work that can happen now.

This should be mergable, provided the specs pass.

**Comment by benogle** [comment]
Whats the appveyor build for?

**Comment by joefitzgerald** [comment]
> Whats the appveyor build for?

It's to verify Windows compatibility. I need to add appveyor.yml.

**Pull request merged**
