### PR TITLE
Support `filterSuggestions` property on providers

### PR DESCRIPTION
**Pull request by benogle**
Closes https://github.com/atom-community/autocomplete-plus/issues/360

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Thoughts on providing filterSuggestions (and potentially others) via serviceHub so that providers can simply depend on autocomplete-plus for common helper functions? This would allow the use of potentially multiple common strategies for filtering / sorting:

* filterSuggestions
* sortSuggestionsPrioritizingExactMatch (yes, horrible name)
* ...etc

**Comment by benogle** [comment]
Can you write a code sample? Or provide further details? I feel that generally it will be complicated, not clean, and wont get us any further than this approach.

**Comment by joefitzgerald** [comment]
> I feel that generally it will be complicated, not clean, and wont get us any further than this approach.

I make the suggestion simply because adding `filterSuggestions` as a property of the provider is likely to cause a proliferation of other requests for autocomplete-plus to essentially perform utility tasks on the suggestions.

I see there being two possible ways to work around putting it on the provider:

1. Pass function(s) in the options object for a suggestion request, providing access to the provider to those functions
1. Provide a service via service-hub that gives providers access to those functions

The above don't preclude some small number of properties on the provider like `filterSuggestions`, but it could allow the library of functions to evolve without affecting the core provider API.

**Comment by benogle** [comment]
I'd rather have only one option that covers the 80% case and have it be easy easy to use. If a provider author wants it to work a different way, they can file an issue/PR (if small change) or they can filter on their own. They are not forced to use this option. I dont want to end up with a bunch of different options _or_ functions for different filtering / sorting behavior. If people ask to add more options, we can say no, and suggestion filtering on their own.

**Comment by joefitzgerald** [comment]
OK, fair enough.

**Pull request merged**
