### PR TITLE
Clean up less styling to use standard classes and colors from styleguide

### PR DESCRIPTION
**Pull request by park9140**

### CODE REVIEW

**Comment by park9140** [comment]
@joefitzgerald, we should probably pull this to resolve #214.  It gets us to a more consistent state at least.

**Comment by joefitzgerald** [comment]
@park9140 you should always feel free to merge and release, on any PR.

**Comment by park9140** [comment]
@joefitzgerald, yeah just wanted to make sure you didn't have anything else before I do it when I get to work.

**Comment by joefitzgerald** [comment]
Nope, go for it.

**Comment by basarat** [comment]
Awesome. I'll update once this is pushed.

**Pull request merged**
