### PR TITLE
Fix engines field in package.json

### PR DESCRIPTION
**Pull request by benogle**
Remove `*` to reduce confusion, and add make sure atom is less than `2.0.0`.

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Oh weird that * was an error.

**Comment by joefitzgerald** [comment]
@benogle can you help me understand why we would want an upper bound to this? The `*` should absolutely be removed.

**Comment by benogle** [comment]
This supports only the atom 1.0 api. It's future proofing for 2.0. We can set it and forget it.

**Review by nejdevyslovit — COMMENTED** [review]
gg

**Pull request merged**
